language: python
dist: xenial
sudo: required

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-accel

os:
  - linux

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
  - python -m pip install -U pip pytest black
  - pip install -e .

script:
  - python -m pytest
  - black --check --diff rpi_backlight tests

skip_join: false
